const BREAK_TIPS = {
  de: [
    "Mache 5 Kniebeugen oder strecke deinen Körper einmal kräftig durch!",
    "Trinke ein großes Glas frisches, kaltes Wasser!",
    "Blicke für 1 Minute aus dem Fenster in die Ferne, um deine Augen zu entspannen!",
    "Schüttle deine Arme und Beine für 15 Sekunden kräftig aus (Dopamin-Reset)!",
    "Atme 5-mal ganz tief durch die Nase ein und langsam durch den Mund wieder aus!"
  ],
  en: [
    "Do 5 squats or stretch your body vigorously!",
    "Drink a large glass of fresh, cold water!",
    "Look out the window into the distance for 1 minute to relax your eyes!",
    "Shake out your arms and legs for 15 seconds (dopamine reset)!",
    "Take 5 deep breaths in through your nose and slowly out through your mouth!"
  ],
  es: [
    "¡Haz 5 sentadillas o estira tu cuerpo con fuerza!",
    "¡Bebe un vaso grande de agua fresca y fría!",
    "¡Mira por la ventana hacia el horizonte durante 1 minuto para relajar los ojos!",
    "¡Sacude tus brazos y piernas con fuerza durante 15 segundos (reajuste de dopamina)!",
    "¡Inhala profundamente 5 veces por la nariz y exhala lentamente por la boca!"
  ],
  el: [
    "Κάνε 5 βαθιά καθίσματα ή τέντωσε το σώμα σου καλά!",
    "Πιες ένα μεγάλο ποτήρι φρέσκο, κρύο νερό!",
    "Κοίταξε έξω από το παράθυρο στο βάθος για 1 λεπτό για να χαλαρώσεις τα μάτια σου!",
    "Τίναξε τα χέρια και τα πόδια σου δυνατά για 15 δευτερόλεπτα (επαναφορά ντοπαμίνης)!",
    "Πάρε 5 βαθιές ανάσες από τη μύτη και εξέπνευσε αργά από το στόμα!"
  ]
};

// Psychologische Micro-Steps zur Überwindung von Blockaden
const DOPAMINE_TASKS = {
  de: [
    "Trinke 3 Schlucke frisches Wasser 💧",
    "Strecke deine Arme 10 Sekunden lang fest Richtung Decke 🙋‍♂️",
    "Räume einen einzigen Gegenstand auf deinem Tisch auf 🧹",
    "Schüttle deine Hände 15 Sekunden lang ganz locker aus 🫨",
    "Atme 3-mal ganz tief durch deine Nase ein und den Mund aus 🌬️",
    "Rolle deine Schultern 5-mal langsam nach hinten 🧘",
    "Lächle dich selbst im Spiegel oder auf dem ausgeschalteten Bildschirm für 10 Sekunden an! 😁",
    "Kreise deine Fußgelenke 5-mal in beide Richtungen 🦶"
  ],
  en: [
    "Drink 3 sips of fresh water 💧",
    "Stretch your arms tightly towards the ceiling for 10 seconds 🙋‍♂️",
    "Tidy up a single object on your desk 🧹",
    "Vigorously shake out your hands for 15 seconds 🫨",
    "Take 3 deep breaths in through your nose and out through your mouth 🌬️",
    "Roll your shoulders slowly backwards 5 times 🧘",
    "Smile at yourself in the mirror or on your black screen for 10 seconds! 😁",
    "Rotate your ankles 5 times in both directions 🦶"
  ],
  es: [
    "Bebe 3 sorbos de agua fresca 💧",
    "Estira tus brazos firmemente hacia el techo durante 10 segundos 🙋‍♂️",
    "Ordena un solo objeto en tu escritorio 🧹",
    "Sacude tus manos muy relajadamente durante 15 segundos 🫨",
    "Inhala profundamente 3 veces por la nariz y exhala por la boca 🌬️",
    "Gira tus hombros lentamente hacia atrás 5 veces 🧘",
    "¡Sonríete al espejo o a tu pantalla apagada durante 10 segundos! 😁",
    "Gira tus tobillos 5 veces en ambas direcciones 🦶"
  ],
  el: [
    "Πιες 3 γουλιές φρέσκο νερό 💧",
    "Τέντωσε τα χέρια σου ψηλά προς το ταβάνι για 10 δευτερόλεπτα 🙋‍♂️",
    "Τακτοποίησε ένα μόνο αντικείμενο στο γραφείο σου 🧹",
    "Τίναξε τα χέρια σου πολύ χαλαρά για 15 δευτερόλεπτα 🫨",
    "Πάρε 3 βαθιές ανάσες από τη μύτη και εξέπνευσε από το στόμα 🌬️",
    "Κύλισε τους ώμους σου αργά προς τα πίσω 5 φορές 🧘",
    "Χαμογέλασε στον εαυτό σου στον καθρέφτη ή στην κλειστή οθόνη για 10 δευτερόλεπτα! 😁",
    "Κάνε κύκλους με τους αστραγάλους σου 5 φορές και προς τις δύο κατευθύνσεις 🦶"
  ]
};

// 40 psychologische und abwechslungsreiche ADHD-Kurzaktivitäten für den Dopamin-Funken
const BOOST_ACTIVITIES = {
  de: [
    "Atme 3-mal tief durch deine Nase ein und gaaaaanz langsam durch deinen Mund wieder aus. 🌬️",
    "Trinke ein großes Glas frisches, kaltes Wasser, um deine Gehirnzellen aufzuwecken! 💧",
    "Rolle deine Schultern 5-mal langsam nach hinten. 🧘",
    "Steh kurz auf, strecke deine Arme fest Richtung Decke aus und mach dich ganz lang. 🙋‍♂️",
    "Kreise deine Hand- und Fußgelenke 5-mal in beide Richtungen. 🦶",
    "Schüttle deine Hände 15 Sekunden lang ganz locker aus (Dopamin-Reset)! 🫨",
    "Blicke für 15 Sekunden aus dem Fenster auf den am weitesten entfernten Punkt. 🌲",
    "Laufe einmal quer durch den Raum, tipp kurz an die Wand und komm wieder zurück! 🏃",
    "Lächle dich selbst im Spiegel oder auf dem schwarzen Bildschirm für 10 Sekunden an! 😁",
    "Massiere deine Ohrmuscheln sanft für 10 Sekunden von oben nach unten. 👂",
    "Schließe deine Augen und nimm 3 verschiedene Geräusche um dich herum bewusst wahr. 🎧",
    "Schneide eine super lustige Grimasse, um deine gesamte Gesichtsmuskulatur zu entspannen! 🤪",
    "Klopfe deine Arme und Beine von oben nach unten sanft ab (Aktivierung). 🫳",
    "Knülle ein Papier zusammen und wirf es als Zielwurf in deinen Papierkorb! 🏀",
    "Tu für 10 Sekunden so, als würdest du ein Musikinstrument wie Luftgitarre spielen! 🎸",
    "Zähle rückwärts von 20 auf 0 in Dreierschritten (20, 17, 14...). 🧠",
    "Öffne deinen Kiefer weit und gähne einmal tief, um Gesichtsspannungen zu lösen! 🥱",
    "Reibe deine Handflächen kräftig aneinander, bis sie richtig schön warm werden! 👐",
    "Trommle deine Finger für 10 Sekunden wie auf einem Klavier auf den Tisch. 🎹",
    "Hüpfe für 10 Sekunden leicht federnd auf der Stelle. ⚡",
    "Summe deine Lieblingsmelodie für 15 Sekunden vor dich hin. 🎵",
    "Umfasse deine Hände hinter dem Rücken und zieh deine Brust nach vorne auf (Dehnen). 🙆‍♀️",
    "Suche einen roten Gegenstand in deiner direkten Umgebung und fokussiere ihn für 5 Sekunden. 🔴",
    "Drücke deine Zungenspitze für 10 Sekunden fest gegen deinen Gaumen. 👅",
    "Mache 5 langsame Kniebeugen, um das Blut in deine Beine zu bringen. 🏋️",
    "Balanciere für 10 Sekunden auf einem Bein und schließe dabei die Augen! 🤸",
    "Knete oder massiere deine Nackenmuskeln mit beiden Händen für 15 Sekunden. 💆‍♂️",
    "Finde einen kreisförmigen Gegenstand im Raum und fahre seine Konturen mit den Augen ab. ⭕",
    "Nimm dir ein Buch oder Magazin und lies ein einziges zufälliges Wort laut vor. 📖",
    "Reibe deine Daumen- und Zeigefingerspitzen für 10 Sekunden aneinander (Sinnreiz). 🤌",
    "Verändere deine Sitzposition um 90 Grad oder sitze für 20 Sekunden kerzengerade aufrecht. 🪑",
    "Mach deine Augen ganz weit auf, kneife sie dann fest zusammen und öffne sie wieder. 👁️",
    "Führe deinen Ellenbogen für 5 Sekunden zum diagonalen Knie (Cross-Crawl). 🏃‍♂️",
    "Bewege deine Zehen in deinen Schuhen oder Socken ganz wild hin und her. 🧦",
    "Nenne 3 Dinge in deinem Kopf, für die du heute dankbar bist. 🌸",
    "Klopfe mit deinen Fingerspitzen ganz sanft dein Gesicht ab (Tapping). 💆‍♀️",
    "Denke an ein Tier, das mit dem Anfangsbuchstaben deines Namens beginnt. 🦁",
    "Atme tief ein, halte die Luft für 4 Sekunden an, und atme langsam wieder aus (Box-Breathing). 🫁",
    "Klopfe dir einmal kräftig selbst auf die Schulter! Das machst du gut. 👏",
    "Spreize deine Finger so weit wie möglich, halte sie für 5 Sekunden und entspanne sie. 🖐️"
  ],
  en: [
    "Take 3 deep breaths in through your nose and exhale veeeery slowly. 🌬️",
    "Drink a large glass of cold water to awaken your brain cells! 💧",
    "Roll your shoulders slowly backwards 5 times. 🧘",
    "Stand up, stretch your arms tightly towards the ceiling and make yourself tall. 🙋‍♂️",
    "Rotate your wrist and ankle joints 5 times in both directions. 🦶",
    "Vigorously shake out your hands for 15 seconds (dopamine reset)! 🫨",
    "Look out the window at the furthest point for 15 seconds. 🌲",
    "Walk once across the room, tap the wall, and come back! 🏃",
    "Smile at yourself in the mirror or black screen for 10 seconds! 😁",
    "Gently massage your earlobes from top to bottom for 10 seconds. 👂",
    "Close your eyes and try to identify 3 different sounds around you. 🎧",
    "Make a funny face to completely relax all your muscles! 🤪",
    "Gently pat down your arms and legs from top to bottom (activation). 🫳",
    "Crumple a piece of paper and throw it into the trash can as a target practice! 🏀",
    "Pretend to play a musical instrument like an air guitar for 10 seconds! 🎸",
    "Count backwards from 20 to 0 in steps of 3 (20, 17, 14...). 🧠",
    "Open your jaw wide and yawn deeply to release facial tension! 🥱",
    "Rub your palms vigorously together until they get really warm! 👐",
    "Drum your fingers on the desk for 10 seconds like on a piano. 🎹",
    "Bounce lightly on the spot for 10 seconds. ⚡",
    "Hum your favorite melody for 15 seconds. 🎵",
    "Clasp your hands behind your back and open up your chest (stretch). 🙆‍♀️",
    "Find a red object in your immediate vicinity and focus on it for 5 seconds. 🔴",
    "Press the tip of your tongue firmly against the roof of your mouth for 10 seconds. 👅",
    "Do 5 slow squats to get the blood pumping into your legs. 🏋️",
    "Balance on one leg for 10 seconds and close your eyes! 🤸",
    "Knead or massage your neck muscles with both hands for 15 seconds. 💆‍♂️",
    "Find a circular object in the room and trace its contours with your eyes. ⭕",
    "Grab a book or magazine and read a single random word out loud. 📖",
    "Rub your thumb and index finger tips together for 10 seconds (sensory stimulation). 🤌",
    "Change your sitting position by 90 degrees or sit up perfectly straight for 20 seconds. 🪑",
    "Open your eyes very wide, squeeze them shut tightly, and open them again. 👁️",
    "Touch your elbow to your opposite knee (cross-crawl exercise) 5 times. 🏃‍♂️",
    "Wiggle your toes inside your shoes or socks wildly back and forth. 🧦",
    "Name 3 things in your mind that you are grateful for today. 🌸",
    "Gently tap your face with your fingertips (tapping technique). 💆‍♀️",
    "Think of an animal that starts with the first letter of your name. 🦁",
    "Inhale deeply, hold your breath for 4 seconds, and exhale slowly (box breathing). 🫁",
    "Give yourself a firm pat on the back! You are doing great. 👏",
    "Spread your fingers as wide as possible, hold for 5 seconds, then relax. 🖐️"
  ],
  es: [
    "Inhala profundamente 3 veces por la nariz y exhala muuuuy despacio por la boca. 🌬️",
    "¡Bebe un vaso grande de agua fresca y fría para despertar tus neuronas! 💧",
    "Gira tus hombros lentamente hacia atrás 5 veces. 🧘",
    "Ponte de pie, estira los brazos con fuerza hacia el techo y hazte alto. 🙋‍♂️",
    "Gira las articulaciones de la muñeca y el tobillo 5 veces en ambas direcciones. 🦶",
    "¡Sacude vigorosamente tus manos durante 15 segundos (reajuste de dopamina)! 🫨",
    "Mira por la ventana hacia el punto más lejano durante 15 segundos. 🌲",
    "¡Camina una vez por la habitación, toca la pared y regresa! 🏃",
    "¡Sonríete a ti mismo en el espejo o en la pantalla apagada durante 10 segundos! 😁",
    "Masajea suavemente los lóbulos de tus orejas de arriba a abajo durante 10 segundos. 👂",
    "Cierra los ojos e intenta identificar 3 sonidos diferentes a tu alrededor. 🎧",
    "¡Haz una mueca divertida para relajar por completo todos tus músculos faciales! 🤪",
    "Golpea suavemente tus brazos y piernas de arriba a abajo (activación). 🫳",
    "¡Arruga un trozo de papel y lánzalo a la papelera como práctica de tiro! 🏀",
    "¡Imagina tocar un instrumento musical como la guitarra de aire durante 10 segundos! 🎸",
    "Cuenta regresivamente de 20 a 0 en pasos de 3 (20, 17, 14...). 🧠",
    "¡Abre bien la mandíbula y bosteza profundamente para liberar la tensión facial! 🥱",
    "¡Frota tus palmas vigorosamente hasta que se calienten bien! 👐",
    "Golpea tus dedos en el escritorio durante 10 segundos como si tocaras el piano. 🎹",
    "Rebota suavemente en el lugar durante 10 segundos. ⚡",
    "Tararea tu melodía favorita durante 15 segundos. 🎵",
    "Junta tus manos detrás de tu espalda y abre el pecho (estiramiento). 🙆‍♀️",
    "Encuentra un objeto rojo en tu entorno inmediato y enfócate en él durante 5 segundos. 🔴",
    "Presiona firmemente la punta de la lengua contra el paladar durante 10 segundos. 👅",
    "Haz 5 sentadillas lentas para bombear sangre a tus piernas. 🏋️",
    "¡Mantén el equilibrio sobre una pierna durante 10 segundos y cierra los ojos! 🤸",
    "Amasa o masajea los músculos del cuello con ambas manos durante 15 segundos. 💆‍♂️",
    "Encuentra un objeto circular en la habitación y sigue sus contornos con los ojos. ⭕",
    "Toma un libro o revista y lee una sola palabra al azar en voz alta. 📖",
    "Frota las yemas de tus pulgares e índices durante 10 segundos (estímulo sensorial). 🤌",
    "Cambia tu posición al sentarte 90 grados o siéntate perfectamente derecho por 20 segundos. 🪑",
    "Abre bien los ojos, apriétalos con fuerza y vuelve a abrirlos. 👁️",
    "Toca tu codo con la rodilla opuesta (ejercicio cruzado) 5 times. 🏃‍♂️",
    "Muebe los dedos de los pies dentro de tus zapatos o calcetines de un lado a otro. 🧦",
    "Menciona mentalmente 3 cosas por las que estés agradecido hoy. 🌸",
    "Golpea suavemente tu rostro con las yemas de tus dedos (técnica de tapping). 💆‍♀️",
    "Piensa en un animal que comience con la primera letra de tu nombre. 🦁",
    "Inhala profundamente, sostén el aire 4 segundos y exhala lentamente (respiración en caja). 🫁",
    "¡Date una palmadita firme en la espalda! Lo estás haciendo genial. 👏",
    "Separa tus dedos lo más posible, mantén la posición 5 segundos y relájate. 🖐️"
  ],
  el: [
    "Πάρε 3 βαθιές ανάσες από τη μύτη και εξέπνευσε πάαααρα πολύ αργά από το στόμα. 🌬️",
    "Πιες ένα μεγάλο ποτήρι κρύο νερό για να ξυπνήσεις τα εγκεφαλικά σου κύτταρα! 💧",
    "Κύλισε τους ώμους σου αργά προς τα πίσω 5 φορές. 🧘",
    "Σήκω όρθιος, τέντωσε τα χέρια σου ψηλά προς το ταβάνι και κάνε το σώμα σου μακρύ. 🙋‍♂️",
    "Περιστρέψτε τις αρθρώσεις των καρπών και των αστραγάλων 5 φορές και προς τις δύο κατευθύνσεις. 🦶",
    "Τίναξε τα χέρια σου δυνατά για 15 δευτερόλεπτα (επαναφορά ντοπαμίνης)! 🫨",
    "Κοίταξε έξω από το παράθυρο στο πιο μακρινό σημείο για 15 δευτερόλεπτα. 🌲",
    "Περπάτησε μια φορά μέσα στο δωμάτιο, άγγιξε τον τοίχο και επέστρεψε! 🏃",
    "Χαμογέλασε στον εαυτό σου στον καθρέφτη ή στην κλειστή οθόνη για 10 δευτερόλεπτα! 😁",
    "Κάνε απαλό μασάζ στους λοβούς των αυτιών σου από πάνω προς τα κάτω για 10 δευτερόλεπτα. 👂",
    "Κλείσε τα μάτια σου και προσπάθησε να αναγνωρίσεις 3 διαφορετικούς ήχους γύρω σου. 🎧",
    "Κάνε μια αστεία γκριμάτσα για να χαλαρώσεις εντελώς όλους τους μυς του προσώπου σου! 🤪",
    "Χτύπησε απαλά τα χέρια και τα πόδια σου από πάνω προς τα κάτω (ενεργοποίηση). 🫳",
    "Τσαλάκωσε ένα χαρτί και πέταξέ το στο καλάθι των αχρήστων ως άσκηση στόχου! 🏀",
    "Προσποιήσου ότι παίζεις ένα μουσικό όργανο όπως αεροκιθάρα για 10 δευτερόλεπτα! 🎸",
    "Μέτρησε αντίστροφα από το 20 έως το 0 με βήματα των 3 (20, 17, 14...). 🧠",
    "Άνοιξε καλά το σαγόνι σου και χασμουρήσου βαθιά για να απελευθερώσεις την ένταση του προσώπου! 🥱",
    "Τρίψε τις παλάμες σου δυνατά μεταξύ τους μέχρι να ζεσταθούν καλά! 👐",
    "Χτύπησε τα δάχτυλά σου στο γραφείο για 10 δευτερόλεπτα σαν να παίζεις πιάνο. 🎹",
    "Αναπήδησε απαλά στο σημείο για 10 δευτερόλεπτα. ⚡",
    "Σιγοτραγούδησε την αγαπημένη σου μελωδία για 15 δευτερόλεπτα. 🎵",
    "Πλέξε τα χέρια σου πίσω από την πλάτη σου και άνοιξε το στήθος σου (διάταση). 🙆‍♀️",
    "Βρες ένα κόκκινο αντικείμενο στον άμεσο χώρο σου και εστίασε σε αυτό για 5 δευτερόλεπτα. 🔴",
    "Πίεσε σταθερά την άκρη της γλώσσας σου στον ουρανίσκο για 10 δευτερόλεπτα. 👅",
    "Κάνε 5 αργά βαθιά καθίσματα για να στείλεις αίμα στα πόδια σου. 🏋️",
    "Ισορρόπησε στο ένα πόδι για 10 δευτερόλεπτα και κλείσε τα μάτια σου! 🤸",
    "Τρίψε ή κάνε μασάζ στους μυς του αυχένα σου και με τα δύο χέρια για 15 δευτερόλεπτα. 💆‍♂️",
    "Βρες ένα κυκλικό αντικείμενο στο δωμάτιο και ακολούθησε το περίγραμμά του με τα μάτια σου. ⭕",
    "Πάρε ένα βιβλίο ή περιοδικό και διάβασε μια τυχαία λέξη δυνατά. 📖",
    "Τρίψε τις άκρες των αντίχειρων και των δεικτών σου για 10 δευτερόλεπτα (αισθητηριακή διέγερση). 🤌",
    "Άλλαξε τη θέση σου στο κάθισμα κατά 90 μοίρες ή κάθισε εντελώς όρθιος για 20 δευτερόλεπτα. 🪑",
    "Άνοιξε διάπλατα τα μάτια σου, σφίξε τα δυνατά και άνοιξέ τα ξανά. 👁️",
    "Άγγιξε τον αγκώνα σου στο αντίθετο γόνατο (σταυρωτή άσκηση) 5 φορές. 🏃‍♂️",
    "Κούνησε τα δάχτυλα των ποδιών σου μέσα στα παπούχσια ή τις κάλτσες σου πέρα δώθε. 🧦",
    "Σκέψου 3 πράγματα για τα οποία είσαι ευγνώμων σήμερα. 🌸",
    "Χτύπησε απαλά το πρόσωπό σου με τις άκρες των δαχτύλων σου (τεχνική tapping). 💆‍♀️",
    "Σκέψου ένα ζώο που αρχίζει με το πρώτο γράμμα του ονόματός σου. 🦁",
    "Είσπνευσε βαθιά, κράτησε την ανάσα σου για 4 δευτερόλεπτα και εξέπνευσε αργά. 🫁",
    "Δώσε ένα χτύπημα επιβράβευσης στην πλάτη σου! Τα πας εξαιρετικά. 👏",
    "Άπλωσε τα δάχτυλά σου όσο το δυνατόν περισσότερο, κράτησέ τα για 5 δευτερόλεπτα και χαλάρωσε. 🖐️"
  ]
}; 
